export const integrations = [
  {
    id: 1,
    name: "WhatsApp Business",
    description: "Mensajería empresarial",
    status: "connected",
    color: "bg-green-500",
    lastSync: "Hace 2 min",
  },
  {
    id: 2,
    name: "Google Calendar",
    description: "Calendarios",
    status: "connected",
    color: "bg-blue-500",
    lastSync: "Hace 10 min",
  },
  {
    id: 3,
    name: "OpenAI",
    description: "IA Generativa",
    status: "pending",
    color: "bg-black",
    lastSync: "Pendiente",
  },
  {
    id: 4,
    name: "Slack",
    description: "Comunicación",
    status: "disconnected",
    color: "bg-purple-600",
    lastSync: "Nunca",
  },
  {
    id: 5,
    name: "AWS",
    description: "Cloud",
    status: "connected",
    color: "bg-orange-500",
    lastSync: "Hace 1 hora",
  },
  {
    id: 6,
    name: "Azure",
    description: "Cloud",
    status: "connected",
    color: "bg-sky-500",
    lastSync: "Hace 3 horas",
  },
];